image: 'maven:3.6.3-jdk-11-slim'

cache:
  paths:
    - .m2/repository

variables:
  PROJECT_ARTIFACT_ID: kypo2-rest-user-and-group
  DEPLOYMENT_INFO_VERSION_FILE: VERSION.txt
  MAVEN_CLI_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  
stages:
  - create_tag
  - build
  - tests
  - docker_image_push

create_tag:
  stage: create_tag
  # https://gitlab.ics.muni.cz/csirt-mu-infra/devops-support/docker-images/csirtmu-docker-common-ci
  image: 'nexus.csirt.muni.cz:5000/csirtmu/common-ci'
  variables:
    GIT_STRATEGY: clone
  script:
    - source /app/export-tag-vars.sh VERSION.txt
    - echo $TAG_VERSION && echo $TAG_MESSAGE
    - /app/import-ssh-key.sh
    - /app/prepare-git.sh
    - /app/set-version-java.sh
    # generate swagger documentation
    - mvn clean compile $MAVEN_CLI_OPTS -DskipTests -Dswagger.skip=false -Dproprietary-repo-url=$PROPRIETARY_REPO_URL
    - git add doc-files/kypo-user-and-group-open-api.yaml
    - git commit -m "Updated Swagger documentation generated."
    - /app/tag-and-push.sh
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - VERSION.txt
  artifacts:
    paths:
    - ./pom.xml
    - ./*/pom.xml
    expire_in: 1 hour
    when: on_success
    
build:
  stage: build
  script:
  - mvn clean install $MAVEN_CLI_OPTS -DskipTests -Dproprietary-repo-url=$PROPRIETARY_REPO_URL
  rules:
  - if: '$CI_COMMIT_BRANCH'
  artifacts:
    paths:
    - $PROJECT_ARTIFACT_ID/target/$PROJECT_ARTIFACT_ID-*.jar
    expire_in: 1 hour
    when: on_success
    
tests:
  stage: tests
  script:
  - mvn test $MAVEN_CLI_OPTS -Dproprietary-repo-url=$PROPRIETARY_REPO_URL
  rules:
  - if: '$CI_COMMIT_BRANCH == "master"'
    changes:
      - VERSION.txt
    when: never
  - if: '$CI_COMMIT_BRANCH'
  
docker_image_push:
  before_script: [] #prevent global before_script from running
  variables:
    CI_CUSTOM_IMAGE_NAME: kypo-uag-service
  stage: docker_image_push
  image:
    name: gcr.io/kaniko-project/executor:v1.3.0-debug
    entrypoint: [ "" ]
  script:
    - export CI_CUSTOM_REGISTRY_IMAGE="${CI_REGISTRY}/${CI_CUSTOM_REGISTRY_PATH}/${CI_CUSTOM_IMAGE_NAME}"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_CUSTOM_REGISTRY_USER\",\"password\":\"$CI_CUSTOM_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_CUSTOM_REGISTRY_IMAGE:$CI_COMMIT_TAG --build-arg PROPRIETARY_REPO_URL=$PROPRIETARY_REPO_URL
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH'
      when: never
