#!/bin/sh
set -e
case "$1" in
    configure)
    cd /opt/kypo2/kypo2-user-and-group
    mvn clean install
    cd /opt/kypo2/kypo2-user-and-group/jars
    API_JAR=$(ls kypo2-api-user-and-group*.jar | tail -n 1)
    if ! [ "$API_JAR" = "kypo2-api-user-and-group.jar" ]; then ln -sf $API_JAR kypo2-api-user-and-group.jar; fi
    PERSISTENCE_JAR=$(ls kypo2-persistence-user-and-group*.jar | tail -n 1)
    if ! [ "$PERSISTENCE_JAR" = "kypo2-persistence-user-and-group" ]; then ln -sf $PERSISTENCE_JAR kypo2-persistence-user-and-group.jar; fi
    REST_JAR=$(ls kypo2-rest-user-and-group*.jar | tail -n 1)
    if ! [ "$REST_JAR" = "kypo2-rest-user-and-group.jar" ]; then ln -sf $REST_JAR kypo2-rest-user-and-group.jar; fi
    SECURITY_JAR=$(ls kypo2-security-user-and-group*.jar | tail -n 1)
    if ! [ "$SECURITY_JAR" = "kypo2-security-user-and-group.jar" ]; then ln -sf $SECURITY_JAR kypo2-security-user-and-group.jar; fi
    SERVICE_JAR=$(ls kypo2-service-user-and-group*.jar | tail -n 1)
    if ! [ "$SERVICE_JAR" = "kypo2-service-user-and-group.jar" ]; then ln -sf $SERVICE_JAR kypo2-service-user-and-group.jar; fi    
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

