#!/bin/sh
set -e
case "$1" in
    configure)

    cd /opt/kypo2/kypo2-user-and-group/jars
    REST_JAR=$(ls -v kypo2-rest-user-and-group*.jar | tail -n 1)
    if ! [ "$REST_JAR" = "kypo2-rest-user-and-group.jar" ]; then ln -sf $REST_JAR kypo2-rest-user-and-group.jar; fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

